---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bloodsql
spec:
  serviceName: "bloodsqlsvc"
  replicas: 1
  selector:
    matchLabels:
      app: bloodsql
  template:
    metadata:
      labels:
        app: bloodsql
    spec:
      containers:
      - name: bloodsql
        image: srinuas/bloodapp:dbimg
        ports:
        - containerPort: 80
          name: web

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        volumeMounts:
        - name: dbvol
          mountPath: /usr/share/nginx/html

  volumeClaimTemplates:
  - metadata:
      name: dbvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
